// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/apple/Desktop/Project/coderstation/coderstation-bgSys/src/pages/Admin/model';
import model_2 from '/Users/apple/Desktop/Project/coderstation/coderstation-bgSys/src/pages/Type/model';

export const models = {
model_1: { namespace: 'Admin.model', model: model_1 },
model_2: { namespace: 'Type.model', model: model_2 },
} as const
