// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export {
  proxy, useSnapshot, snapshot, subscribe,
  proxyWithComputed,
  proxyWithHistory,
  proxyWithDevtools,
  proxyMap,
  proxySet,
} from '/Users/apple/Desktop/Project/coderstation/coderstation-bgSys/node_modules/@umijs/valtio';
